trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'

- script: dotnet restore CartNest/CartNest.csproj
  displayName: 'Restore packages'

- script: dotnet build CartNest/CartNest.csproj --configuration $(buildConfiguration)
  displayName: 'Build'

- script: dotnet publish CartNest/CartNest.csproj --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
  displayName: 'Publish'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'CartNest-ServiceConnection'
    appType: 'webApp'
    appName: 'CartNest'
    package: '$(Build.ArtifactStagingDirectory)/**/*.zip'